### ISSUE TITLE
Second imbuement recipe overrides first imbuement recipe at same recipeID

### ISSUE THREAD

**Issue by tonby** [MasterOfBob777/kjsarsnouveau#1]
I used "event.recipes.ars_nouveau.imbuement()" method in a same script. Then, the latter overrides the former.

Example: https://imgur.com/a/dgTUUHl
I wrote as the first screenshot.
The recipe A is added as the second screenshot.
Then I remove the comment-out in recipe B from the script.
The recipe A is removed and the recipe B is added at the same recipeID as third screenshot.

version:
Minecraft: 1.19.2
Forge: 43.2.4
KubeJS: kubejs-forge-1902.6.0-build.142
Ars Nouveau: ars_nouveau-1.19.2-3.12.3
KubeJS Ars Nouveau: kubejsarsnoveau-1.0

**Comment by MasterOfBob777** [comment]
This now works for me locally with the newest version, could you see if it works for you?

**Comment by tonby** [comment]
I confirmed it fixed in the newest version. Thank you.

**Comment by MasterOfBob777** [comment]
No problem!
